name: if_inclusivo
description: "Projeto Flutter para frontend do IFInclusivo"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  youtube_player_flutter: ^8.1.2
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  provider: ^6.1.2
  google_fonts: ^6.3.1
  go_router_builder: ^3.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  result_dart: ^2.0.0
  result_command: ^1.3.0
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  lucid_validation: ^1.3.1
  web: ^1.1.1
  timeago: ^3.7.1
  flutter_quill: ^11.4.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.4.5
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/footer/
    - assets/icons/
    - assets/login_register/
    - assets/card_libras_icons/
    - assets/env/.env
    - assets/logo/
    - assets/exceptions/
